channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - libffi=3.4.2
  - ncurses=6.4
  - openssl=1.1.1t
  - pip=23.0.1
  - python=3.11.2
  - readline=8.2
  - setuptools=65.6.3
  - sqlite=3.41.1
  - tk=8.6.12
  - tzdata=2022g
  - wheel=0.38.4
  - xz=5.2.10
  - zlib=1.2.13
  - pip:
    - arpeggio==2.0.0
    - click==7.1.2
    - contourpy==1.0.7
    - cycler==0.11.0
    - filelock==3.10.7
    - fonttools==4.39.3
    - jinja2==3.1.2
    - kiwisolver==1.4.4
    - markupsafe==2.1.2
    - matplotlib==3.7.1
    - mpmath==1.3.0
    - networkx==3.0
    - numpy==1.24.2
    - opt-einsum==3.3.0
    - packaging==23.0
    - pandas==1.5.3
    - pillow==9.4.0
    - pyparsing==3.0.9
    - pyro-api==0.1.2
    - pyro-ppl==1.8.4
    - python-dateutil==2.8.2
    - pytz==2023.3
    - seaborn==0.12.2
    - six==1.16.0
    - sympy==1.11.1
    - textx==3.1.1
    - torch==2.0.0
    - tqdm==4.65.0
    - typing-extensions==4.5.0
