channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=3.6.2
  - appnope=0.1.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.2.1
  - attrs=22.2.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.12.0
  - bleach=6.0.0
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cffi=1.15.1
  - comm=0.1.3
  - debugpy=1.6.6
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=1.2.0
  - flit-core=3.8.0
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=58.2
  - idna=3.4
  - importlib-metadata=6.1.0
  - importlib_metadata=6.1.0
  - importlib_resources=5.12.0
  - ipykernel=6.22.0
  - ipython=8.12.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.6
  - jedi=0.18.2
  - jinja2=3.1.2
  - jpeg=9e
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=8.1.0
  - jupyter_console=6.6.3
  - jupyter_core=5.3.0
  - jupyter_events=0.6.3
  - jupyter_server=2.5.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab_pygments=0.2.2
  - jupyterlab_widgets=3.0.7
  - krb5=1.19.3
  - lerc=3.0
  - libclang=12.0.0
  - libcxx=16.0.0
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libffi=3.4.2
  - libiconv=1.17
  - libllvm12=12.0.1
  - libpng=1.6.39
  - libpq=12.9
  - libsodium=1.0.18
  - libtiff=4.5.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lz4-c=1.9.4
  - markupsafe=2.1.2
  - matplotlib-inline=0.1.6
  - mistune=2.0.5
  - nbclassic=0.5.3
  - nbclient=0.7.2
  - nbconvert=7.2.10
  - nbconvert-core=7.2.10
  - nbconvert-pandoc=7.2.10
  - nbformat=5.8.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - notebook=6.5.3
  - notebook-shim=0.2.2
  - nspr=4.35
  - nss=3.74
  - openssl=1.1.1t
  - packaging=23.0
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.0.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.2.0
  - ply=3.11
  - prometheus_client=0.16.0
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - psutil=5.9.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.14.0
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.19.3
  - python=3.11.2
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.3
  - python-json-logger=2.0.7
  - python_abi=3.11
  - pyyaml=6.0
  - pyzmq=25.0.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole=5.4.1
  - qtconsole-base=5.4.1
  - qtpy=2.3.1
  - qtwebkit=5.212
  - readline=8.2
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - send2trash=1.8.0
  - setuptools=65.6.3
  - sip=6.6.2
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.3.2.post1
  - sqlite=3.41.1
  - stack_data=0.6.2
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.2
  - traitlets=5.9.0
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzdata=2022g
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - websocket-client=1.5.1
  - wheel=0.38.4
  - widgetsnbextension=4.0.7
  - xz=5.2.10
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.4
  - pip:
    - arpeggio==2.0.0
    - click==7.1.2
    - contourpy==1.0.7
    - cycler==0.11.0
    - filelock==3.10.7
    - fonttools==4.39.3
    - kiwisolver==1.4.4
    - matplotlib==3.7.1
    - mpmath==1.3.0
    - networkx==3.0
    - numpy==1.24.2
    - opt-einsum==3.3.0
    - pandas==1.5.3
    - pillow==9.4.0
    - pyparsing==3.0.9
    - pyro-api==0.1.2
    - pyro-ppl==1.8.4
    - pytz==2023.3
    - seaborn==0.12.2
    - sympy==1.11.1
    - textx==3.1.1
    - torch==2.0.0
    - tqdm==4.65.0
    - z3-solver==4.12.1.0
